### ISSUE TITLE
replace phantomjs with headless chrome

### ISSUE THREAD

**Issue by art-in** [art-in/microcosm#54]
chrome can run in `--headless` mode in all environments since v60  

no reason to use `phantomjs` anymore, as its dev is too slow to support latest specs (eg. es6 Proxy)

**Comment by artin-phares** [comment]
karma cannot start `ChromeHeadless`
 `Chrome v61`, `karma v1.7.1` (+ `v1.5.0`), `windows 7`

```
WARN [launcher]: ChromeHeadless have not captured in 180000 ms, killing.
```

**Comment by artin-phares** [comment]
staying with `phantomjs` for now

**Comment by artin-phares** [comment]
`phantomjs` removed, using headless chrome by default  

on windows stay with windowed chrome until capturing issue is fixed

**Comment by artin-phares** [comment]
working workaround https://github.com/karma-runner/karma/issues/2652#issuecomment-335599121

**Comment by art-in** [comment]
closing, as not running tests in windows anymore, using docker container with ubuntu for dev env.
